version: '3.8'

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:2.9.1
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - CADDY_DOCKER_PROCESS_CADDYFILE=true
      - CADDY_DOCKER_PROXY_SERVICE_TASKS=true
      - CADDY_INGRESS_NETWORKS=caddy-proxy
    volumes:
      - ${CADDY_DATA_VOLUME:-/mnt/nfs/caddy/data}:/data
      - ${CADDY_CONFIG_VOLUME:-/mnt/nfs/caddy/config}:/config
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - caddy-proxy
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  caddy-proxy:
    external: true