version: '3.8'

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:2.9.1
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - CADDY_CLUSTERING=consul://consul:8500
      - CADDY_INGRESS_NETWORKS=caddy-proxy
      - CADDY_DOCKER_PROXY_SERVICE_TASKS=true
      - CADDY_DOCKER_PROCESS_CADDYFILE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /nfs/portainer/caddy/data:/data
      - /nfs/portainer/caddy/config:/config
    networks:
      - caddy-proxy
      - consul-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  caddy-proxy:
    external: true
  consul-net:
    external: true