version: '3.8'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    environment:
      - OLLAMA_API_BASE_URL=${OLLAMA_API_BASE_URL}
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
    volumes:
      - ${WEBUI_DATA_PATH}:/app/backend/data
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true 