## Deze config is alleen voor Docker Swarm

version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.swarmmode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-proxy"
      # Entrypoints
      - "--entrypoints.web.address=:${TRAEFIK_ENTRYPOINT_HTTP}"
      - "--entrypoints.websecure.address=:${TRAEFIK_ENTRYPOINT_HTTPS}"
      # ACME configuratie met staging
      - "--certificatesresolvers.default.acme.email=${TRAEFIK_LETSENCRYPT_MAIL}"
      - "--certificatesresolvers.default.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.default.acme.httpchallenge=true"
      - "--certificatesresolvers.default.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.default.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      # Logging
      - "--log.level=DEBUG"
      - "--accesslog=true"

    ports:
      - target: ${TRAEFIK_ENTRYPOINT_HTTP}
        published: ${TRAEFIK_ENTRYPOINT_HTTP}
        mode: host
        protocol: tcp
      - target: ${TRAEFIK_ENTRYPOINT_HTTPS}
        published: ${TRAEFIK_ENTRYPOINT_HTTPS}
        mode: host
        protocol: tcp

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${STORAGE_LOCATION}/letsencrypt:/letsencrypt

    networks:
      - traefik-proxy

    deploy:
      mode: replicated
      replicas: 3  # Tijdelijk naar 1 voor troubleshooting
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        
        # ACME HTTP Challenge Router
        - "traefik.http.routers.acme-http.entrypoints=web"
        - "traefik.http.routers.acme-http.rule=Host(`${TRAEFIK_DASHBOARD_URL}`) && PathPrefix(`/.well-known/acme-challenge/`)"
        - "traefik.http.routers.acme-http.service=api@internal"
        - "traefik.http.routers.acme-http.priority=999"
        - "traefik.http.routers.acme-http.tls=false"
        
        # Dashboard configuratie
        - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_DASHBOARD_URL}`)"
        - "traefik.http.routers.dashboard.service=api@internal"
        - "traefik.http.routers.dashboard.entrypoints=websecure"
        - "traefik.http.routers.dashboard.middlewares=dashboard-auth,dashboard-ipallowlist"
        - "traefik.http.routers.dashboard.tls=true"
        - "traefik.http.routers.dashboard.tls.certresolver=default"
        - "traefik.http.routers.dashboard.priority=1"
        
        # Middlewares
        - "traefik.http.middlewares.dashboard-auth.basicauth.users=${TRAEFIK_DASHBOARD_AUTH_USER}"
        - "traefik.http.middlewares.dashboard-ipallowlist.ipwhitelist.sourcerange=${TRAEFIK_DASHBOARD_IPWITHLIST}"
      endpoints:
        - targetPort: ${TRAEFIK_ENTRYPOINT_HTTP}
          publishedPort: ${TRAEFIK_ENTRYPOINT_HTTP}
          protocol: tcp
        - targetPort: ${TRAEFIK_ENTRYPOINT_HTTPS}
          publishedPort: ${TRAEFIK_ENTRYPOINT_HTTPS}
          protocol: tcp

networks:
  traefik-proxy:
    external: true
