## Deze config is alleen voor Docker swarm

version: "3.9"

services:
  traefik:
    image: "traefik:${TRAEFIK_VERSION}"
    command:
      - "--api=true"
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:${TRAEFIK_ENTRYPOINT_HTTP}"
      - "--entrypoints.websecure.address=:${TRAEFIK_ENTRYPOINT_HTTPS}"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--accesslog=true"
      - "--log.level=DEBUG"
      - "--certificatesresolvers.default.acme.tlschallenge=true"
      - "--certificatesresolvers.default.acme.email=${TRAEFIK_LETSENCRYPT_MAIL}"
      - "--certificatesresolvers.default.acme.storage=/letsencrypt/acme.json"
    ports:
      - target: ${TRAEFIK_ENTRYPOINT_HTTP}
        published: ${TRAEFIK_ENTRYPOINT_HTTP}
        mode: host
      - target: ${TRAEFIK_ENTRYPOINT_HTTPS}
        published: ${TRAEFIK_ENTRYPOINT_HTTPS}
        mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/nfs/portainer/letsencrypt:/letsencrypt"
    deploy:
      mode: global # Draai Traefik op alle nodes
    networks:
      - traefik-proxy
    environment:
      - TRAEFIK_ENTRYPOINT_HTTP=${TRAEFIK_ENTRYPOINT_HTTP}
      - TRAEFIK_ENTRYPOINT_HTTPS=${TRAEFIK_ENTRYPOINT_HTTPS}
    labels:
      - "traefik.enable=true"

      # Router configuratie voor het dashboard
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_DASHBOARD_URL}`)"
      - "traefik.http.routers.dashboard.service=api@internal"

      # Middleware koppelen (IP-whitelist en Basic Auth)
      - "traefik.http.routers.dashboard.middlewares=ip-allowlist@docker,auth@docker"

      # IPWhitelist Middleware
      - "traefik.http.middlewares.ip-allowlist.ipallowlist.sourcerange=${TRAEFIK_DASHBOARD_IPWITHLIST}"

      # Basic Auth Middleware
      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_DASHBOARD_AUTH_USER}:${TRAEFIK_DASHBOARD_AUTH_PASSWORD_HASH}"

networks:
  traefik-proxy:
    driver: overlay # Overlay-netwerk voor Swarm
