## Deze config is alleen voor Docker Swarm

version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--log.level=DEBUG"  # Extra debugging
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-proxy"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # ACME (Let's Encrypt) configuratie 
      - "--certificatesresolvers.default.acme.httpchallenge=true"
      - "--certificatesresolvers.default.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.default.acme.email=${TRAEFIK_LETSENCRYPT_MAIL}"
      - "--certificatesresolvers.default.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.default.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"  # Staging server
      # Geen HTTPS redirect tijdens testen
      - "--entrypoints.web.http.redirections.entrypoint.enable=false"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
      - target: 443
        published: 443
        protocol: tcp
        mode: ingress
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${STORAGE_LOCATION}/letsencrypt:/letsencrypt

    networks:
      - traefik-proxy
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        # ACME HTTP Challenge route (moet eerst komen)
        - "traefik.http.routers.acme.rule=PathPrefix(`/.well-known/acme-challenge/`)"
        - "traefik.http.routers.acme.entrypoints=web"
        - "traefik.http.routers.acme.service=api@internal"
        - "traefik.http.routers.acme.priority=999"
        - "traefik.http.routers.acme.tls=false"
        # Dashboard configuratie
        - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DASHBOARD_URL}`)"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.routers.traefik.entrypoints=websecure"
        - "traefik.http.routers.traefik.tls.certresolver=default"
        - "traefik.http.routers.traefik.middlewares=traefik-auth,traefik-ipwhitelist"
        # Deze niet weghalen ander port missing error
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
        # Auth & IP whitelist
        - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_AUTH_USER}:${TRAEFIK_DASHBOARD_AUTH_PASSWORD_HASH}"
        - "traefik.http.middlewares.traefik-ipwhitelist.ipwhitelist.sourcerange=${TRAEFIK_DASHBOARD_IPWITHLIST}"

networks:
  traefik-proxy:
    external: true
