## Deze config is alleen voor Docker Swarm

version: '3.8'

services:
  traefik:
    image: traefik:${TRAEFIK_VERSION}
    command:
      - "--api"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-proxy"
      - "--entrypoints.web.address=:${TRAEFIK_ENTRYPOINT_HTTP}"
      - "--entrypoints.websecure.address=:${TRAEFIK_ENTRYPOINT_HTTPS}"
      - "--certificatesresolvers.default.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.default.acme.email=${TRAEFIK_LETSENCRYPT_MAIL}"
      - "--certificatesresolvers.default.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.default.acme.httpchallenge=true"
      - "--certificatesresolvers.default.acme.httpchallenge.entrypoint=web"
      - "--entrypoints.web.http.redirections.entrypoint.enabled=false"
      - "--log.level=DEBUG"
    ports:
      - target: ${TRAEFIK_ENTRYPOINT_HTTP}
        published: ${TRAEFIK_ENTRYPOINT_HTTP}
        mode: host
      - target: ${TRAEFIK_ENTRYPOINT_HTTPS}
        published: ${TRAEFIK_ENTRYPOINT_HTTPS}
        mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/nfs/portainer/traefik/letsencrypt:/letsencrypt"
      - "/nfs/portainer/traefik/logs:/var/log"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_DASHBOARD_URL}`)"
        - "traefik.http.routers.dashboard.service=api@internal"
        - "traefik.http.routers.dashboard.entrypoints=websecure"
        - "traefik.http.routers.dashboard.middlewares=dashboard-auth,dashboard-ipallowlist"
        - "traefik.http.routers.dashboard.tls=true"
        - "traefik.http.routers.dashboard.tls.certresolver=default"
        - "traefik.http.middlewares.dashboard-ipallowlist.ipallowlist.sourcerange=${TRAEFIK_DASHBOARD_IPWITHLIST}"
        - "traefik.http.middlewares.dashboard-auth.basicauth.users=${TRAEFIK_DASHBOARD_AUTH_USER}:${TRAEFIK_DASHBOARD_AUTH_PASSWORD_HASH}"

networks:
  traefik-proxy:
    external: true
    name: traefik-proxy
    driver: overlay
