version: '3.8'

services:
  traefik:
    image: traefik:v3.0
    command:
      - "--log.level=DEBUG"
      - "--log.format=json"
      - "--accesslog=true"
      - "--accesslog.format=json"
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-public"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.dashboard.address=:8080"
      - "--certificatesresolvers.ovhdns.acme.dnschallenge=true"
      - "--certificatesresolvers.ovhdns.acme.dnschallenge.provider=ovh"
      - "--certificatesresolvers.ovhdns.acme.email=${TRAEFIK_ACME_EMAIL}"
      - "--certificatesresolvers.ovhdns.acme.storage=/etc/traefik/letsencrypt/acme.json"
      - "--certificatesresolvers.ovhdns.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
      - target: 443
        published: 443
        protocol: tcp
        mode: ingress
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
    environment:
      - OVH_ENDPOINT=${OVH_ENDPOINT}
      - OVH_APPLICATION_KEY=${OVH_APPLICATION_KEY}
      - OVH_APPLICATION_SECRET=${OVH_APPLICATION_SECRET}
      - OVH_CONSUMER_KEY=${OVH_CONSUMER_KEY}
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.role == manager
        max_replicas_per_node: 1
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      labels:
        # Global Traefik enable
        - traefik.enable=true
        # Dashboard router
        - traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_DASHBOARD_HOST}`)
        - traefik.http.routers.dashboard.entrypoints=websecure
        - traefik.http.routers.dashboard.service=api@internal
        - traefik.http.routers.dashboard.tls.certresolver=ovhdns
        # Dashboard auth
        - traefik.http.routers.dashboard.middlewares=dashboard-auth
        - traefik.http.middlewares.dashboard-auth.basicauth.users=${TRAEFIK_DASHBOARD_USER}:${TRAEFIK_DASHBOARD_PASSWORD}
    volumes:
      - ${TRAEFIK_DATA_PATH}/letsencrypt:/etc/traefik/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  traefik-public:
    external: true 