## Deze config is alleen voor Docker Swarm

version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.swarmmode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-proxy"
      # Entrypoints
      - "--entrypoints.web.address=:${TRAEFIK_ENTRYPOINT_HTTP}"
      - "--entrypoints.websecure.address=:${TRAEFIK_ENTRYPOINT_HTTPS}"
      # ACME configuratie
      - "--certificatesresolvers.default.acme.email=${TRAEFIK_LETSENCRYPT_MAIL}"
      - "--certificatesresolvers.default.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.default.acme.httpchallenge=true"
      - "--certificatesresolvers.default.acme.httpchallenge.entrypoint=web"
      # Logging
      - "--log.level=INFO"
      - "--accesslog=true"

    ports:
      - target: ${TRAEFIK_ENTRYPOINT_HTTP}
        published: ${TRAEFIK_ENTRYPOINT_HTTP}
        mode: host
        protocol: tcp
      - target: ${TRAEFIK_ENTRYPOINT_HTTPS}
        published: ${TRAEFIK_ENTRYPOINT_HTTPS}
        mode: host
        protocol: tcp

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${STORAGE_LOCATION}/letsencrypt:/letsencrypt

    networks:
      - traefik-proxy

    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        # Dashboard configuratie
        - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_DASHBOARD_URL}`)"
        - "traefik.http.routers.dashboard.service=api@internal"
        - "traefik.http.routers.dashboard.entrypoints=websecure"
        - "traefik.http.routers.dashboard.middlewares=dashboard-auth,dashboard-ipallowlist"
        - "traefik.http.routers.dashboard.tls=true"
        - "traefik.http.routers.dashboard.tls.certresolver=default"
        
        # ACME HTTP Challenge Router
        - "traefik.http.routers.acme.rule=PathPrefix(`/.well-known/acme-challenge/`)"
        - "traefik.http.routers.acme.entrypoints=web"
        - "traefik.http.routers.acme.service=api@internal"
        - "traefik.http.routers.acme.priority=255"
        
        # Expliciet port mapping voor de service
        - "traefik.http.services.api.loadbalancer.server.port=8080"
        - "traefik.http.services.api.loadbalancer.server.scheme=http"
        
        # Middlewares
        - "traefik.http.middlewares.dashboard-auth.basicauth.users=${TRAEFIK_DASHBOARD_AUTH_USER}:${TRAEFIK_DASHBOARD_AUTH_PASSWORD_HASH}"
        - "traefik.http.middlewares.dashboard-ipallowlist.ipwhitelist.sourcerange=${TRAEFIK_DASHBOARD_IPWITHLIST}"

networks:
  traefik-proxy:
    external: true
