version: '3.8'

services:
  postgresql:
    image: postgres:15-alpine
    user: ${PUID}:${PGID}
    environment:
      - POSTGRES_USER=gitlab
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=gitlabhq_production
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    networks:
      - gitlab-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gitlab -d gitlabhq_production"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    user: ${PUID}:${PGID}
    volumes:
      - ${REDIS_DATA_PATH}:/data
    networks:
      - gitlab-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  gitlab:
    image: gitlab/gitlab-ce:latest
    environment:
      GITLAB_ROOT_PASSWORD: "${GITLAB_ROOT_PASSWORD}"
      GITLAB_OMNIBUS_CONFIG: "
        external_url '${GITLAB_EXTERNAL_URL}';
        gitlab_rails['db_adapter'] = 'postgresql';
        gitlab_rails['db_host'] = 'postgresql';
        gitlab_rails['db_port'] = 5432;
        gitlab_rails['db_database'] = 'gitlabhq_production';
        gitlab_rails['db_username'] = 'gitlab';
        gitlab_rails['db_password'] = '${POSTGRES_PASSWORD}';
        gitlab_rails['redis_host'] = 'redis';
        nginx['listen_addresses'] = ['0.0.0.0'];
        nginx['listen_port'] = 80;
        nginx['listen_https'] = false;
        nginx['proxy_set_headers'] = {
          'X-Forwarded-Proto' => 'https',
          'X-Forwarded-Ssl' => 'on',
          'Host' => '$http_host'
        };
        gitlab_workhorse['listen_network'] = 'tcp';
        gitlab_workhorse['listen_addr'] = '0.0.0.0:8181';
        gitlab_rails['omniauth_enabled'] = true;
        gitlab_rails['omniauth_allow_single_sign_on'] = ['openid_connect'];
        gitlab_rails['omniauth_sync_email_from_provider'] = 'openid_connect';
        gitlab_rails['omniauth_sync_profile_from_provider'] = ['openid_connect'];
        gitlab_rails['omniauth_sync_profile_attributes'] = ['email'];
        gitlab_rails['omniauth_auto_sign_in_with_provider'] = 'openid_connect';
        gitlab_rails['omniauth_block_auto_created_users'] = false;
        gitlab_rails['omniauth_auto_link_saml_user'] = true;
        gitlab_rails['omniauth_auto_link_user'] = ['openid_connect'];
        gitlab_rails['omniauth_providers'] = [
          {
            'name' => 'openid_connect',
            'label' => 'Authentik',
            'args' => {
              'name' => 'openid_connect',
              'scope' => ['openid', 'profile', 'email', 'groups'],
              'response_type' => 'code',
              'issuer' => 'https://auth.mbitc.nl/application/o/gitlab/',
              'discovery' => true,
              'client_auth_method' => 'query',
              'uid_field' => 'preferred_username',
              'send_scope_to_token_endpoint' => true,
              'pkce' => true,
              'verify_ssl' => false,
              'client_options' => {
                'identifier' => '${AUTHENTIK_CLIENT_ID}',
                'secret' => '${AUTHENTIK_CLIENT_SECRET}',
                'redirect_uri' => '${GITLAB_EXTERNAL_URL}/users/auth/openid_connect/callback'
              }
            }
          }
        ];
      "
    volumes:
      - ${GITLAB_CONFIG_PATH}:/etc/gitlab
      - ${GITLAB_LOGS_PATH}:/var/log/gitlab
      - ${GITLAB_DATA_PATH}:/var/opt/gitlab
    networks:
      - gitlab-network
      - traefik-public
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.gitlab-secure.rule=Host(`${GITLAB_DOMAIN}`)"
        - "traefik.http.routers.gitlab-secure.entrypoints=websecure"
        - "traefik.http.routers.gitlab-secure.tls=true"
        - "traefik.http.routers.gitlab-secure.tls.certresolver=ovhdns"
        - "traefik.http.services.gitlab-secure.loadbalancer.server.port=80"
    depends_on:
      - postgresql
      - redis

networks:
  gitlab-network:
    external: true
    name: gitlab-network
  traefik-public:
    external: true
    name: traefik-public
    driver: overlay
