version: '3.8'

services:
  wud:
    image: fmartinou/whats-up-docker:latest
    container_name: wud
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Europe/Amsterdam}
      # Configuratie voor Docker Swarm monitoring
      - WUD_DOCKER_SOCKET_PATH=/var/run/docker.sock
      - WUD_DOCKER_SWARM=true
      # Configuratie voor WUD UI
      - WUD_UI=true
      - WUD_UI_HOST=0.0.0.0
      - WUD_UI_PORT=${WUD_UI_PORT:-3000}
      # GEEN authenticatie configuratie meer - dit wordt door Traefik afgehandeld
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${WUD_DATA_PATH:-./data}:/store
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.wud.rule=Host(`${WUD_SUBDOMAIN:-wud}.${DNS_NAME}`)"
        - "traefik.http.routers.wud.entrypoints=websecure"
        - "traefik.http.routers.wud.tls=true"
        - "traefik.http.routers.wud.tls.certresolver=ovhdns"
        - "traefik.http.services.wud.loadbalancer.server.port=${WUD_UI_PORT:-3000}"
        # Authentik Forward Auth configuratie
        - "traefik.http.routers.wud.middlewares=authentik-auth@docker"
        - "traefik.http.middlewares.authentik-auth.forwardauth.address=https://auth.mbitc.nl:9443/outpost.goauthentik.io/auth/traefik"
        - "traefik.http.middlewares.authentik-auth.forwardauth.trustForwardHeader=true"
        - "traefik.http.middlewares.authentik-auth.forwardauth.authResponseHeaders=X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid"
    networks:
      - traefik-public
      - authentik-intern  # Voeg Authentik netwerk toe om met Authentik te kunnen communiceren
    ports:
      - "3005:3000"

networks:
  traefik-public:
    external: true
  authentik-intern:
    external: true
