version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    deploy:
      mode: replicated
      replicas: 1  # Ollama draait als single instance voor model management
      labels:
        - "traefik.enable=true"
        # Router configuratie voor Ollama API
        - "traefik.http.routers.ollama-api.rule=Host(`${OLLAMA_API_DOMAIN}`)"
        - "traefik.http.routers.ollama-api.entrypoints=websecure"
        - "traefik.http.routers.ollama-api.tls=true"
        - "traefik.http.routers.ollama-api.tls.certresolver=default"
        # Service configuratie
        - "traefik.http.services.ollama-api.loadbalancer.server.port=11434"
        # Optionele beveiliging
        - "traefik.http.routers.ollama-api.middlewares=ip-allowlist@docker"
        - "traefik.http.middlewares.ip-allowlist.ipallowlist.sourcerange=${OLLAMA_API_ALLOWED_IPS}"
    networks:
      - ai-net
    volumes:
      - ${OLLAMA_DATA_PATH}:/root/.ollama  # Persistent storage voor models

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    networks:
      - traefik-proxy
      - ai-net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        # Service definitie met expliciete naam
        - "traefik.http.services.open-webui.loadbalancer.server.port=8080"
        - "traefik.http.services.open-webui.loadbalancer.passHostHeader=true"
        - "traefik.http.services.open-webui.loadbalancer.sticky.cookie=true"
        # HTTPS router
        - "traefik.http.routers.open-webui-secure.rule=Host(`${OPENWEBUI_DOMAIN}`)"
        - "traefik.http.routers.open-webui-secure.entrypoints=websecure"
        - "traefik.http.routers.open-webui-secure.service=open-webui"
        - "traefik.http.routers.open-webui-secure.tls=true"
        - "traefik.http.routers.open-webui-secure.tls.certresolver=default"
        # HTTP router (voor ACME)
        - "traefik.http.routers.open-webui-http.rule=Host(`${OPENWEBUI_DOMAIN}`)"
        - "traefik.http.routers.open-webui-http.entrypoints=web"
        - "traefik.http.routers.open-webui-http.service=open-webui"
    volumes:
      - ${OPENWEBUI_DATA_PATH}:/app/backend/data  # Gebruikt env variable voor volume path

networks:
  ai-net:
    driver: overlay
  traefik-proxy:
    external: true
    name: traefik_traefik-proxy

volumes:
  ollama_data:
    driver: local 
  open_webui_data:    # Nieuw volume toevoegen
    driver: local