version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    deploy:
      mode: replicated
      replicas: 1  # Ollama draait als single instance voor model management
      labels:
        - "traefik.enable=true"
        # Router configuratie voor Ollama API
        - "traefik.http.routers.ollama-api.rule=Host(`${OLLAMA_API_DOMAIN}`)"
        - "traefik.http.routers.ollama-api.entrypoints=websecure"
        - "traefik.http.routers.ollama-api.tls=true"
        - "traefik.http.routers.ollama-api.tls.certresolver=default"
        # Service configuratie
        - "traefik.http.services.ollama-api.loadbalancer.server.port=11434"
        # Optionele beveiliging
        - "traefik.http.routers.ollama-api.middlewares=ip-allowlist@docker"
        - "traefik.http.middlewares.ip-allowlist.ipallowlist.sourcerange=${OLLAMA_API_ALLOWED_IPS}"
    networks:
      - ai-net
    volumes:
      - ${OLLAMA_DATA_PATH}:/root/.ollama  # Persistent storage voor models

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434/api
      - WEBUI_JWT_SECRET_KEY=${WEBUI_JWT_SECRET_KEY}
      - WEBUI_DB_PATH=/app/backend/data/database.db
      - WEBUI_AUTH=true
      - WEBUI_HOST=0.0.0.0
      - WEBUI_PORT=8080
      # ... andere environment variables ...
    networks:
      - traefik-proxy
      - ai-net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        # Service definitie
        - "traefik.http.services.open-webui.loadbalancer.server.port=8080"
        - "traefik.http.services.open-webui.loadbalancer.passHostHeader=true"
        # HTTPS router
        - "traefik.http.routers.open-webui.rule=Host(`${OPENWEBUI_DOMAIN}`)"
        - "traefik.http.routers.open-webui.entrypoints=websecure"
        - "traefik.http.routers.open-webui.service=open-webui"
        - "traefik.http.routers.open-webui.tls=true"
        - "traefik.http.routers.open-webui.tls.certresolver=default"

networks:
  ai-net:
    driver: overlay
  traefik-proxy:
    external: true
    name: traefik_traefik-proxy

volumes:
  ollama_data:
    driver: local 
  open_webui_data:    # Nieuw volume toevoegen
    driver: local