version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /nfs/portainer/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /nfs/portainer/nginx/certs:/etc/nginx/certs:ro
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - nginx-net

networks:
  nginx-net:
    driver: overlay
