version: '3.8'

services:
  grav:
    image: lscr.io/linuxserver/grav:latest
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grav.rule=Host(`www.mbitc.nl`) || Host(`mbitc.nl`)"
        - "traefik.http.routers.grav.entrypoints=web"
        - "traefik.http.routers.grav.middlewares=redirect-to-https"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        - "traefik.http.routers.grav-secure.rule=Host(`www.mbitc.nl`) || Host(`mbitc.nl`)"
        - "traefik.http.routers.grav-secure.entrypoints=websecure"
        - "traefik.http.routers.grav-secure.tls=true"
        - "traefik.http.routers.grav-secure.tls.certresolver=letsencrypt"
        - "traefik.http.services.grav.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik-proxy"
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - /nfs/portainer/grav:/config
    networks:
      - traefik-proxy
    restart: unless-stopped

volumes:
  grav_config:
    driver: local

networks:
  traefik-proxy:
    external: true
