version: '3.8'

services:
  grav:
    image: lscr.io/linuxserver/grav:latest
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grav.rule=Host(`www.mbitc.nl`) || Host(`mbitc.nl`)"
        - "traefik.http.routers.grav.service=grav-service"
        - "traefik.http.routers.grav.entrypoints=websecure"
        - "traefik.http.routers.grav.tls=true"
        - "traefik.http.routers.grav.tls.certresolver=default"
        - "traefik.http.services.grav-service.loadbalancer.server.port=80"
        - "traefik.http.services.grav-service.loadbalancer.passHostHeader=true"
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - /nfs/portainer/grav:/config
    networks:
      - traefik-proxy
    restart: unless-stopped

volumes:
  grav_config:
    driver: local

networks:
  traefik-proxy:
    external: true
