version: '3.8'

services:
  grav:
    image: lscr.io/linuxserver/grav:latest
    deploy:
      replicas: 1
      labels:
        caddy: mbitc.nl
        caddy.reverse_proxy: "{{upstreams 80}}"
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - /nfs/portainer/grav:/config
    networks:
      - caddy-proxy
    restart: unless-stopped

volumes:
  grav_config:
    driver: local

networks:
  caddy-proxy:
    external: true
