version: "3.5"

services:
  bunkerweb:
    image: bunkerity/bunkerweb:1.5.12
    ports:
      - published: 80
        target: 8080
        mode: host
        protocol: tcp
      - published: 443
        target: 8443
        mode: host
        protocol: tcp
    environment:
      - SERVER_NAME=${SERVER_NAME:-}
      - DATABASE_URI=mariadb+pymysql://${MYSQL_USER:-bunkerweb}:${MYSQL_PASSWORD}@${MYSQL_HOST:-bw-db}:3306/${MYSQL_DATABASE:-db}
      - SWARM_MODE=${SWARM_MODE:-yes}
      - MULTISITE=${MULTISITE:-yes}
      - USE_REDIS=${USE_REDIS:-yes}
      - REDIS_HOST=${REDIS_HOST:-bw-redis}
      - API_WHITELIST_IP=${API_WHITELIST_IP:-127.0.0.0/8 10.20.30.0/24}
    networks:
      - bw-universe
      - bw-services
    deploy:
      mode: global
      placement:
        constraints:
          - "node.role == worker"
      labels:
        - "bunkerweb.INSTANCE=yes"

  bw-autoconf:
    image: bunkerity/bunkerweb-autoconf:1.5.12
    environment:
      - SWARM_MODE=${SWARM_MODE:-yes}
      - DOCKER_HOST=${DOCKER_HOST:-tcp://bw-docker:2375}
      - DATABASE_URI=mariadb+pymysql://${MYSQL_USER:-bunkerweb}:${MYSQL_PASSWORD}@${MYSQL_HOST:-bw-db}:3306/${MYSQL_DATABASE:-db}
    networks:
      - bw-universe
      - bw-docker
    deploy:
      placement:
        constraints:
          - "node.role == worker"

  bw-docker:
    image: tecnativa/docker-socket-proxy:nightly
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONFIGS=1
      - CONTAINERS=1
      - SERVICES=1
      - SWARM=1
      - TASKS=1
      - LOG_LEVEL=${LOG_LEVEL:-warning}
    networks:
      - bw-docker
    deploy:
      placement:
        constraints:
          - "node.role == manager"

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:1.5.12
    environment:
      - SWARM_MODE=${SWARM_MODE:-yes}
      - DOCKER_HOST=${DOCKER_HOST:-tcp://bw-docker:2375}
      - DATABASE_URI=mariadb+pymysql://${MYSQL_USER:-bunkerweb}:${MYSQL_PASSWORD}@${MYSQL_HOST:-bw-db}:3306/${MYSQL_DATABASE:-db}
    networks:
      - bw-universe
      - bw-docker
    deploy:
      placement:
        constraints:
          - "node.role == worker"

  bw-db:
    image: mariadb:10.10
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${MYSQL_DATABASE:-db}
      - MYSQL_USER=${MYSQL_USER:-bunkerweb}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ${NFS_PATH:-/mnt/nfs}/bunkerweb/mariadb:/var/lib/mysql
    networks:
      - bw-docker
    deploy:
      placement:
        constraints:
          - "node.role == worker"

  bw-redis:
    image: redis:7-alpine
    volumes:
      - ${NFS_PATH:-/mnt/nfs}/bunkerweb/redis:/data
    networks:
      - bw-universe
    deploy:
      placement:
        constraints:
          - "node.role == worker"

networks:
  bw-universe:
    name: bw-universe
    driver: overlay
    attachable: true
    ipam:
      config:
        - subnet: ${BW_UNIVERSE_SUBNET:-10.20.30.0/24}
  bw-services:
    name: bw-services
    driver: overlay
    attachable: true
  bw-docker:
    name: bw-docker
    driver: overlay
    attachable: true 