services:
    semaphore:
        #ports:
        #    - 3000:3000
        image: semaphoreui/semaphore:v2.10.43
        environment:
            SEMAPHORE_DB_DIALECT: ${SEMAPHORE_DB_DIALECT}
            SEMAPHORE_ADMIN: ${SEMAPHORE_ADMIN}
            SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_ADMIN_PASSWORD}
            SEMAPHORE_ADMIN_NAME: ${SEMAPHORE_ADMIN_NAME}
            SEMAPHORE_ADMIN_EMAIL: ${SEMAPHORE_ADMIN_EMAIL}
            SEMAPHORE_DATA_PATH: ${SEMAPHORE_DATA_PATH}
            SEMAPHORE_CONFIG_PATH: ${SEMAPHORE_CONFIG_PATH}
            SEMAPHORE_TEMP_PATH: ${SEMAPHORE_TEMP_PATH}
        volumes:
            - ${SEMAPHORE_DATA_PATH}:/var/lib/semaphore
            - ${SEMAPHORE_CONFIG_PATH}:/etc/semaphore
            - ${SEMAPHORE_TEMP_PATH}:/tmp/semaphore
        networks:
            - proxy-network

networks:
    proxy-network:
        external: true